spring:
  cloud:
    function:
      definition: consumer;producer
    stream:
      kafka:
        bindings:
          producer-out-0:
            producer:
              configuration:
                value.serializer: com.example.demokafkacloudstreamer.MessageSerializer
          consumer-in-0:
            consumer:
              configuration:
                value.deserializer: com.example.demokafkacloudstreamer.MessageDeSerializer
                
        binder:
          brokers: localhost:9092
            
      bindings:
        producer-out-0:
            destination : send-events
            producer:
                useNativeEncoding: true # This enables using the custom serializer
        consumer-in-0:
            destination : send-events
            consumer:
              use-native-decoding: true # This enables using the custom deserializer
              concurrency: 3
              